### ISSUE TITLE
Add `.complete` and `.error` methods, and add `onComplete` listeners.

### ISSUE THREAD

**Issue by RangerMauve** [allain/observable-react-state#1]
Dream API:

```javascript

class WebsocketConnection extends ObservableReactState {
	state = {
		ws: null
	}
	constructor(url) {
		this.setState({
			ws: new Websocket(url)
		});
	}
	onComplete() {
		this.state.ws.close()
	}
}

var connection = new WebsocketConnection("example.com");

// Some time later

connection.complete();
```

**Comment by allain** [comment]
Can you explain what the problem you're trying to solve with this might be?

I think you might be able to get what you're after by doing this something like this:

```js
class WebsocketConnection extends ObservableReactState {
	state = {
		ws: null
	}
	constructor(url) {
                super()

                const socket = new Websocket(url)
                socket.on('error', error => this.setState({error})
                socket.on('close', () => this.setState({ws: null})
                // etc

		this.setState({ ws: socket });
	}
	close() { 
		this.state.ws.close()
	}
}

const connection = new WebsocketConnection("example.com");

// Some time later

connection.close();
```

**Comment by RangerMauve** [comment]
That's a good point.

Originally I was thinking it would be useful to have a standard way to have lifecycles for ObservableReactState instances, so if you got a reference to one, there was a standard way to clear it. But I guess that could be built over top of it.

But you should have a way to expose `_stream.complete()` and `_stream.error()` in the public API so people can notify to subscribers to do cleanup.

**Comment by allain** [comment]
Not going to implement since I'm not sure what it would mean for a state object to be in a completed or errored state.
